version: '2'
services:
  bosoftback-app:
    image: bosoftback
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bosoftback-postgresql:5432/BosoftBack
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  bosoftback-postgresql:
    extends:
      file: postgresql.yml
      service: bosoftback-postgresql
